//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.Report.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReportEntities : DbContext
    {
        public ReportEntities()
            : base("name=ReportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RPT_Fac_User_Map> RPT_Fac_User_Map { get; set; }
        public DbSet<RPT_Menu> RPT_Menu { get; set; }
        public DbSet<RPT_User> RPT_User { get; set; }
        public DbSet<RPT_Company> RPT_Company { get; set; }
        public DbSet<RPT_Role> RPT_Role { get; set; }
        public DbSet<RPT_UserRole> RPT_UserRole { get; set; }
        public DbSet<RPT_UserRolePriv> RPT_UserRolePriv { get; set; }
        public DbSet<RPT_UserCompany> RPT_UserCompany { get; set; }
    }
}
