//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace I.Report.DAL
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class RPT_Company
    {
        public int ID { get; set; }
        public string SystemID { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public string ConnectStr { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string FileServerUserAccount { get; set; }
        public string FileServerUserPassword { get; set; }
        public string FileServerAddress { get; set; }
    }
}
