//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或删除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///  查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加失败 的本地化字符串。
        /// </summary>
        internal static string Add_failure {
            get {
                return ResourceManager.GetString("Add failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加信息 的本地化字符串。
        /// </summary>
        internal static string Add_information {
            get {
                return ResourceManager.GetString("Add information", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 增加分区信息 的本地化字符串。
        /// </summary>
        internal static string Add_PartInfo {
            get {
                return ResourceManager.GetString("Add PartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加角色信息 的本地化字符串。
        /// </summary>
        internal static string Add_role_information {
            get {
                return ResourceManager.GetString("Add role information", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加机械站 的本地化字符串。
        /// </summary>
        internal static string Add_Rote_Station {
            get {
                return ResourceManager.GetString("Add Rote Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加路由配置 的本地化字符串。
        /// </summary>
        internal static string Add_Route_Config {
            get {
                return ResourceManager.GetString("Add Route Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加成功! 的本地化字符串。
        /// </summary>
        internal static string Add_Success {
            get {
                return ResourceManager.GetString("Add Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 添加工作集 的本地化字符串。
        /// </summary>
        internal static string Add_Work_Setp {
            get {
                return ResourceManager.GetString("Add Work Setp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确定提交吗 的本地化字符串。
        /// </summary>
        internal static string Are_you_Sure_to_submit {
            get {
                return ResourceManager.GetString("Are you Sure to submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否确认删除此条数据 的本地化字符串。
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_this_data {
            get {
                return ResourceManager.GetString("Are you sure you want to delete this data", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 你确定要注销吗 的本地化字符串。
        /// </summary>
        internal static string Are_you_sure_you_want_to_logout {
            get {
                return ResourceManager.GetString("Are you sure you want to logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 副标题 的本地化字符串。
        /// </summary>
        internal static string Aside_Title {
            get {
                return ResourceManager.GetString("Aside Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 可用菜单 的本地化字符串。
        /// </summary>
        internal static string Available_menu {
            get {
                return ResourceManager.GetString("Available menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 可用角色 的本地化字符串。
        /// </summary>
        internal static string Available_roles {
            get {
                return ResourceManager.GetString("Available roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 条码跟踪查询 的本地化字符串。
        /// </summary>
        internal static string Bar_code_tracing_query {
            get {
                return ResourceManager.GetString("Bar code tracing query", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 条码跟踪 的本地化字符串。
        /// </summary>
        internal static string Bar_code_tracking {
            get {
                return ResourceManager.GetString("Bar code tracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 基本数据 的本地化字符串。
        /// </summary>
        internal static string Basic_data {
            get {
                return ResourceManager.GetString("Basic data", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改密码 的本地化字符串。
        /// </summary>
        internal static string Change_Password {
            get {
                return ResourceManager.GetString("Change Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 中文 的本地化字符串。
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 公司 的本地化字符串。
        /// </summary>
        internal static string Commpany {
            get {
                return ResourceManager.GetString("Commpany", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确认密码 的本地化字符串。
        /// </summary>
        internal static string confirm_password {
            get {
                return ResourceManager.GetString("confirm password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确认提交 的本地化字符串。
        /// </summary>
        internal static string Confirm_submission {
            get {
                return ResourceManager.GetString("Confirm submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 符合 的本地化字符串。
        /// </summary>
        internal static string Conform {
            get {
                return ResourceManager.GetString("Conform", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 版权所有2020中国上海 的本地化字符串。
        /// </summary>
        internal static string Copyright_copy_2020_Shanghai_China_In_fine {
            get {
                return ResourceManager.GetString("Copyright copy 2020 Shanghai China In fine", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 版权所有&amp;2020中国上海因文 的本地化字符串。
        /// </summary>
        internal static string Copyright__copy__2020_Shanghai_China_Infine {
            get {
                return ResourceManager.GetString("Copyright &copy; 2020 Shanghai.China Infine", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创造者 的本地化字符串。
        /// </summary>
        internal static string CreateMachine {
            get {
                return ResourceManager.GetString("CreateMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建时间 的本地化字符串。
        /// </summary>
        internal static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建机器名称 的本地化字符串。
        /// </summary>
        internal static string Create_machine_name {
            get {
                return ResourceManager.GetString("Create machine name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建用户 的本地化字符串。
        /// </summary>
        internal static string Create_user {
            get {
                return ResourceManager.GetString("Create user", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建机器 的本地化字符串。
        /// </summary>
        internal static string Creating_machines {
            get {
                return ResourceManager.GetString("Creating machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创建时间 的本地化字符串。
        /// </summary>
        internal static string Creation_time {
            get {
                return ResourceManager.GetString("Creation time", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 当前角色 的本地化字符串。
        /// </summary>
        internal static string Current_role {
            get {
                return ResourceManager.GetString("Current role", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 直流配置信息 的本地化字符串。
        /// </summary>
        internal static string DC_configuration_information {
            get {
                return ResourceManager.GetString("DC configuration information", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除失败 的本地化字符串。
        /// </summary>
        internal static string Deletion_failed {
            get {
                return ResourceManager.GetString("Deletion failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string Deletion_succeeded {
            get {
                return ResourceManager.GetString("Deletion succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 说明 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Determine {
            get {
                return ResourceManager.GetString("Determine", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 显示 的本地化字符串。
        /// </summary>
        internal static string Displaying {
            get {
                return ResourceManager.GetString("Displaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑失败 的本地化字符串。
        /// </summary>
        internal static string Edit_failure {
            get {
                return ResourceManager.GetString("Edit failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑分区信息 的本地化字符串。
        /// </summary>
        internal static string Edit_PartInfo {
            get {
                return ResourceManager.GetString("Edit PartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑机械站 的本地化字符串。
        /// </summary>
        internal static string Edit_Rote_Station {
            get {
                return ResourceManager.GetString("Edit Rote Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑成功 的本地化字符串。
        /// </summary>
        internal static string Edit_success {
            get {
                return ResourceManager.GetString("Edit success", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编辑工作集 的本地化字符串。
        /// </summary>
        internal static string Edit_Work_Setp {
            get {
                return ResourceManager.GetString("Edit Work Setp", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 英文 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 项目名称 的本地化字符串。
        /// </summary>
        internal static string Entry_name {
            get {
                return ResourceManager.GetString("Entry name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 基本信息 的本地化字符串。
        /// </summary>
        internal static string Essential_information {
            get {
                return ResourceManager.GetString("Essential information", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 现有菜单 的本地化字符串。
        /// </summary>
        internal static string Existing_menu {
            get {
                return ResourceManager.GetString("Existing menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 退出失败 的本地化字符串。
        /// </summary>
        internal static string Exit_failure {
            get {
                return ResourceManager.GetString("Exit failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 出口 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 工厂 的本地化字符串。
        /// </summary>
        internal static string Factory {
            get {
                return ResourceManager.GetString("Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 工厂代码 的本地化字符串。
        /// </summary>
        internal static string Factory_code {
            get {
                return ResourceManager.GetString("Factory code", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 工厂代码不能为空 的本地化字符串。
        /// </summary>
        internal static string Factory_code_cannot_be_empty {
            get {
                return ResourceManager.GetString("Factory code cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 创办人 的本地化字符串。
        /// </summary>
        internal static string Founder {
            get {
                return ResourceManager.GetString("Founder", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 功能代码 的本地化字符串。
        /// </summary>
        internal static string Funciton_Code {
            get {
                return ResourceManager.GetString("Funciton Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 功能名称 的本地化字符串。
        /// </summary>
        internal static string Funtion_Name {
            get {
                return ResourceManager.GetString("Funtion Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 凝胶 的本地化字符串。
        /// </summary>
        internal static string Gel {
            get {
                return ResourceManager.GetString("Gel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 Infine 可追溯系统[V2.0] 的本地化字符串。
        /// </summary>
        internal static string Infine_traceability_system_V2_0_ {
            get {
                return ResourceManager.GetString("Infine traceability system[V2.0]", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信息 的本地化字符串。
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 信息列表 的本地化字符串。
        /// </summary>
        internal static string Information_list {
            get {
                return ResourceManager.GetString("Information list", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 精细可追溯系统 的本地化字符串。
        /// </summary>
        internal static string In_fine_traceability_system {
            get {
                return ResourceManager.GetString("In fine traceability system", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 总共 的本地化字符串。
        /// </summary>
        internal static string in_total {
            get {
                return ResourceManager.GetString("in total", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 项目 的本地化字符串。
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 项目名称 的本地化字符串。
        /// </summary>
        internal static string Item_Name {
            get {
                return ResourceManager.GetString("Item Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 物品种类 的本地化字符串。
        /// </summary>
        internal static string Item_type {
            get {
                return ResourceManager.GetString("Item type", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 项目价值 的本地化字符串。
        /// </summary>
        internal static string Item_Value {
            get {
                return ResourceManager.GetString("Item Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 工作编号 的本地化字符串。
        /// </summary>
        internal static string Job_number {
            get {
                return ResourceManager.GetString("Job number", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 记录查询 的本地化字符串。
        /// </summary>
        internal static string Light_record_query {
            get {
                return ResourceManager.GetString("Light record query", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 林斯密码 的本地化字符串。
        /// </summary>
        internal static string lince_code {
            get {
                return ResourceManager.GetString("lince code", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 线路名称 的本地化字符串。
        /// </summary>
        internal static string Line_Name {
            get {
                return ResourceManager.GetString("Line Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 材料工艺 的本地化字符串。
        /// </summary>
        internal static string Material_technology {
            get {
                return ResourceManager.GetString("Material technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 材料 的本地化字符串。
        /// </summary>
        internal static string MeterialDescrition {
            get {
                return ResourceManager.GetString("MeterialDescrition", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 型号代码 的本地化字符串。
        /// </summary>
        internal static string Model_code {
            get {
                return ResourceManager.GetString("Model code", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 型号名称 的本地化字符串。
        /// </summary>
        internal static string Model_name {
            get {
                return ResourceManager.GetString("Model name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改失败 的本地化字符串。
        /// </summary>
        internal static string Modification_failed {
            get {
                return ResourceManager.GetString("Modification failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改成功 的本地化字符串。
        /// </summary>
        internal static string Modification_succeeded {
            get {
                return ResourceManager.GetString("Modification succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改时间 的本地化字符串。
        /// </summary>
        internal static string Modification_time {
            get {
                return ResourceManager.GetString("Modification time", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改人 的本地化字符串。
        /// </summary>
        internal static string Modified_by {
            get {
                return ResourceManager.GetString("Modified by", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 改装机 的本地化字符串。
        /// </summary>
        internal static string ModifyMachine {
            get {
                return ResourceManager.GetString("ModifyMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改信息 的本地化字符串。
        /// </summary>
        internal static string Modify_information {
            get {
                return ResourceManager.GetString("Modify information", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改机器名称 的本地化字符串。
        /// </summary>
        internal static string Modify_machine_name {
            get {
                return ResourceManager.GetString("Modify machine name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改角色信息 的本地化字符串。
        /// </summary>
        internal static string Modify_role_information {
            get {
                return ResourceManager.GetString("Modify role information", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改时间 的本地化字符串。
        /// </summary>
        internal static string modify_time {
            get {
                return ResourceManager.GetString("modify time", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改用户 的本地化字符串。
        /// </summary>
        internal static string Modify_user {
            get {
                return ResourceManager.GetString("Modify user", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 必要选择要修改的数据 的本地化字符串。
        /// </summary>
        internal static string Must_Select_the_data_to_modify {
            get {
                return ResourceManager.GetString("Must Select the data to modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 导航菜单 的本地化字符串。
        /// </summary>
        internal static string Navigation_menu {
            get {
                return ResourceManager.GetString("Navigation menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string newly_build {
            get {
                return ResourceManager.GetString("newly build", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新信息 的本地化字符串。
        /// </summary>
        internal static string New_information {
            get {
                return ResourceManager.GetString("New information", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 新密码 的本地化字符串。
        /// </summary>
        internal static string new_password {
            get {
                return ResourceManager.GetString("new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 否 的本地化字符串。
        /// </summary>
        internal static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 未选择行 的本地化字符串。
        /// </summary>
        internal static string No_rows_are_selected {
            get {
                return ResourceManager.GetString("No rows are selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 的 的本地化字符串。
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 操作时间 的本地化字符串。
        /// </summary>
        internal static string Operation_time {
            get {
                return ResourceManager.GetString("Operation time", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 原始密码 的本地化字符串。
        /// </summary>
        internal static string original_password {
            get {
                return ResourceManager.GetString("original password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 页 的本地化字符串。
        /// </summary>
        internal static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 参数描述 的本地化字符串。
        /// </summary>
        internal static string ParamDesc {
            get {
                return ResourceManager.GetString("ParamDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 参数名 的本地化字符串。
        /// </summary>
        internal static string ParamName {
            get {
                return ResourceManager.GetString("ParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 参数值 的本地化字符串。
        /// </summary>
        internal static string ParamValue {
            get {
                return ResourceManager.GetString("ParamValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 部分说明 的本地化字符串。
        /// </summary>
        internal static string Partial_description {
            get {
                return ResourceManager.GetString("Partial description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 分区信息 的本地化字符串。
        /// </summary>
        internal static string PartInfo {
            get {
                return ResourceManager.GetString("PartInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 零件级 的本地化字符串。
        /// </summary>
        internal static string PartLevel {
            get {
                return ResourceManager.GetString("PartLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 零件 的本地化字符串。
        /// </summary>
        internal static string PartNo {
            get {
                return ResourceManager.GetString("PartNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 零件描述 的本地化字符串。
        /// </summary>
        internal static string Part_Description {
            get {
                return ResourceManager.GetString("Part Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 零件信息 的本地化字符串。
        /// </summary>
        internal static string Part_information {
            get {
                return ResourceManager.GetString("Part information", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 零件号 的本地化字符串。
        /// </summary>
        internal static string Part_number {
            get {
                return ResourceManager.GetString("Part number", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密码更改 的本地化字符串。
        /// </summary>
        internal static string Password_Change {
            get {
                return ResourceManager.GetString("Password Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密码更改成功 的本地化字符串。
        /// </summary>
        internal static string password_changed_successfully {
            get {
                return ResourceManager.GetString("password changed successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请重新输入密码 的本地化字符串。
        /// </summary>
        internal static string Please_enter_the_password_again {
            get {
                return ResourceManager.GetString("Please enter the password again", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请输入你的密码 的本地化字符串。
        /// </summary>
        internal static string Please_enter_your_password {
            get {
                return ResourceManager.GetString("Please enter your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请填写角色编号 的本地化字符串。
        /// </summary>
        internal static string Please_fill_in_the_role_number {
            get {
                return ResourceManager.GetString("Please fill in the role number", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请记住你的新密码 的本地化字符串。
        /// </summary>
        internal static string Please_remember_your_new_password {
            get {
                return ResourceManager.GetString("Please remember your new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择 的本地化字符串。
        /// </summary>
        internal static string Please_select {
            get {
                return ResourceManager.GetString("Please select", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择部件 的本地化字符串。
        /// </summary>
        internal static string Please_Select_Part {
            get {
                return ResourceManager.GetString("Please Select Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择路线 的本地化字符串。
        /// </summary>
        internal static string Please_Select_Route {
            get {
                return ResourceManager.GetString("Please Select Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择要配置的数据 的本地化字符串。
        /// </summary>
        internal static string Please_select_the_data_to_configure {
            get {
                return ResourceManager.GetString("Please select the data to configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择要删除的数据 的本地化字符串。
        /// </summary>
        internal static string Please_Select_the_data_to_delete {
            get {
                return ResourceManager.GetString("Please Select the data to delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择要编辑的数据 的本地化字符串。
        /// </summary>
        internal static string Please_Select_the_data_to_edit {
            get {
                return ResourceManager.GetString("Please Select the data to edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择要修改的信息 的本地化字符串。
        /// </summary>
        internal static string Please_select_the_data_to_modify {
            get {
                return ResourceManager.GetString("Please select the data to modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择要删除的信息 的本地化字符串。
        /// </summary>
        internal static string Please_select_the_information_to_delete {
            get {
                return ResourceManager.GetString("Please select the information to delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择要更新的参数 的本地化字符串。
        /// </summary>
        internal static string Please_Select_the_parameters_to_update {
            get {
                return ResourceManager.GetString("Please Select the parameters to update", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 请选择工艺站 的本地化字符串。
        /// </summary>
        internal static string Please_select_the_process_station_first {
            get {
                return ResourceManager.GetString("Please select the process station first", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 打印机号不能为空 的本地化字符串。
        /// </summary>
        internal static string Printer_number_cannot_be_empty {
            get {
                return ResourceManager.GetString("Printer number cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 过程 的本地化字符串。
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 流程代码 的本地化字符串。
        /// </summary>
        internal static string Process_code {
            get {
                return ResourceManager.GetString("Process code", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 过程描述 的本地化字符串。
        /// </summary>
        internal static string Process_Desc {
            get {
                return ResourceManager.GetString("Process Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 流程说明 的本地化字符串。
        /// </summary>
        internal static string Process_description {
            get {
                return ResourceManager.GetString("Process description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 过程信息 的本地化字符串。
        /// </summary>
        internal static string process_info {
            get {
                return ResourceManager.GetString("process info", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 进程名称 的本地化字符串。
        /// </summary>
        internal static string Process_name {
            get {
                return ResourceManager.GetString("Process name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 进程名不能为空 的本地化字符串。
        /// </summary>
        internal static string process_name_cannot_be_empty {
            get {
                return ResourceManager.GetString("process name cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 项目名称 的本地化字符串。
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 最近登录的机器 的本地化字符串。
        /// </summary>
        internal static string Recently_logged_in_machines {
            get {
                return ResourceManager.GetString("Recently logged in machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 报告查询 的本地化字符串。
        /// </summary>
        internal static string Report_query {
            get {
                return ResourceManager.GetString("Report query", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 结果 的本地化字符串。
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改者 的本地化字符串。
        /// </summary>
        internal static string Reviser {
            get {
                return ResourceManager.GetString("Reviser", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色描述 的本地化字符串。
        /// </summary>
        internal static string Role_description {
            get {
                return ResourceManager.GetString("Role description", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色ID 的本地化字符串。
        /// </summary>
        internal static string Role_ID {
            get {
                return ResourceManager.GetString("Role ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色信息 的本地化字符串。
        /// </summary>
        internal static string Role_information {
            get {
                return ResourceManager.GetString("Role information", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色管理 的本地化字符串。
        /// </summary>
        internal static string Role_management {
            get {
                return ResourceManager.GetString("Role management", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色名称 的本地化字符串。
        /// </summary>
        internal static string Role_name {
            get {
                return ResourceManager.GetString("Role name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 角色编号 的本地化字符串。
        /// </summary>
        internal static string Role_number {
            get {
                return ResourceManager.GetString("Role number", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 红色 的本地化字符串。
        /// </summary>
        internal static string Rote_Code {
            get {
                return ResourceManager.GetString("Rote Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 机械名 的本地化字符串。
        /// </summary>
        internal static string Rote_Name {
            get {
                return ResourceManager.GetString("Rote Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 机械站 的本地化字符串。
        /// </summary>
        internal static string Rote_Station {
            get {
                return ResourceManager.GetString("Rote Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 烂路 的本地化字符串。
        /// </summary>
        internal static string Rotten_Road {
            get {
                return ResourceManager.GetString("Rotten Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 路由配置信息 的本地化字符串。
        /// </summary>
        internal static string Route_Config_Info {
            get {
                return ResourceManager.GetString("Route Config Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 行号 的本地化字符串。
        /// </summary>
        internal static string row_num {
            get {
                return ResourceManager.GetString("row num", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 螺丝编号 的本地化字符串。
        /// </summary>
        internal static string Screw_No {
            get {
                return ResourceManager.GetString("Screw No", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 螺丝编号 的本地化字符串。
        /// </summary>
        internal static string Screw_number {
            get {
                return ResourceManager.GetString("Screw number", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 序列号 的本地化字符串。
        /// </summary>
        internal static string serial_number {
            get {
                return ResourceManager.GetString("serial number", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 车站代码 的本地化字符串。
        /// </summary>
        internal static string station_code {
            get {
                return ResourceManager.GetString("station code", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 车站编码 的本地化字符串。
        /// </summary>
        internal static string Station_coding {
            get {
                return ResourceManager.GetString("Station coding", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 车站名称 的本地化字符串。
        /// </summary>
        internal static string Station_name {
            get {
                return ResourceManager.GetString("Station name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 站号 的本地化字符串。
        /// </summary>
        internal static string Station_number {
            get {
                return ResourceManager.GetString("Station number", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 步骤说明 的本地化字符串。
        /// </summary>
        internal static string Step_Desc {
            get {
                return ResourceManager.GetString("Step Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 步骤信息 的本地化字符串。
        /// </summary>
        internal static string Step_Info {
            get {
                return ResourceManager.GetString("Step Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 步骤名 的本地化字符串。
        /// </summary>
        internal static string Step_Name {
            get {
                return ResourceManager.GetString("Step Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 步骤号 的本地化字符串。
        /// </summary>
        internal static string Step_No {
            get {
                return ResourceManager.GetString("Step No", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 步骤参数 的本地化字符串。
        /// </summary>
        internal static string Step_Param {
            get {
                return ResourceManager.GetString("Step Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 步骤类型 的本地化字符串。
        /// </summary>
        internal static string Step_Type {
            get {
                return ResourceManager.GetString("Step Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提交 的本地化字符串。
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提交成功 的本地化字符串。
        /// </summary>
        internal static string Submitted_successfully {
            get {
                return ResourceManager.GetString("Submitted successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统信息 的本地化字符串。
        /// </summary>
        internal static string system_info {
            get {
                return ResourceManager.GetString("system info", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 系统管理 的本地化字符串。
        /// </summary>
        internal static string system_management {
            get {
                return ResourceManager.GetString("system management", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 特克 的本地化字符串。
        /// </summary>
        internal static string Teke {
            get {
                return ResourceManager.GetString("Teke", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 第 的本地化字符串。
        /// </summary>
        internal static string The_first {
            get {
                return ResourceManager.GetString("The first", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 材料不能为空 的本地化字符串。
        /// </summary>
        internal static string The_Material_cannot_be_empty {
            get {
                return ResourceManager.GetString("The Material cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 物料描述不能为空 的本地化字符串。
        /// </summary>
        internal static string The_MeterialDescrition_cannot_be_empty {
            get {
                return ResourceManager.GetString("The MeterialDescrition cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 部件说明不能为空 的本地化字符串。
        /// </summary>
        internal static string The_PartDescription_cannot_be_empty {
            get {
                return ResourceManager.GetString("The PartDescription cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 零件级不能为空 的本地化字符串。
        /// </summary>
        internal static string The_PartLevel_cannot_be_empty {
            get {
                return ResourceManager.GetString("The PartLevel cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 零件号不能为空 的本地化字符串。
        /// </summary>
        internal static string The_PartNo_cannot_be_empty {
            get {
                return ResourceManager.GetString("The PartNo cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 密码不匹配,请重新输入 的本地化字符串。
        /// </summary>
        internal static string The_passwords_do_not_match__Please_re_enter {
            get {
                return ResourceManager.GetString("The passwords do not match, Please re-enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 项目名称不能为空 的本地化字符串。
        /// </summary>
        internal static string The_ProjectName_cannot_be_empty {
            get {
                return ResourceManager.GetString("The ProjectName cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 现在的角色 的本地化字符串。
        /// </summary>
        internal static string The_role_now {
            get {
                return ResourceManager.GetString("The role now", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 到 的本地化字符串。
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 扭矩 的本地化字符串。
        /// </summary>
        internal static string Torque {
            get {
                return ResourceManager.GetString("Torque", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 跟踪报告登录 的本地化字符串。
        /// </summary>
        internal static string Trace_Report_Login {
            get {
                return ResourceManager.GetString("Trace Report Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更新失败 的本地化字符串。
        /// </summary>
        internal static string Update_failed {
            get {
                return ResourceManager.GetString("Update failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更新信息 的本地化字符串。
        /// </summary>
        internal static string update_info {
            get {
                return ResourceManager.GetString("update info", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 修改成功 的本地化字符串。
        /// </summary>
        internal static string Update_Success {
            get {
                return ResourceManager.GetString("Update Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 更新工作步骤参数 的本地化字符串。
        /// </summary>
        internal static string Update_work_step_parameters {
            get {
                return ResourceManager.GetString("Update work step parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户账号 的本地化字符串。
        /// </summary>
        internal static string User_account {
            get {
                return ResourceManager.GetString("User account", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户账户不能为空 的本地化字符串。
        /// </summary>
        internal static string User_account_cannot_be_empty {
            get {
                return ResourceManager.GetString("User account cannot be empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户管理 的本地化字符串。
        /// </summary>
        internal static string user_management {
            get {
                return ResourceManager.GetString("user management", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string User_name {
            get {
                return ResourceManager.GetString("User name", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户密码 的本地化字符串。
        /// </summary>
        internal static string User_password {
            get {
                return ResourceManager.GetString("User password", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 用户角色 的本地化字符串。
        /// </summary>
        internal static string User_role {
            get {
                return ResourceManager.GetString("User role", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 使用此区域可提供其他信息 的本地化字符串。
        /// </summary>
        internal static string Use_this_area_to_provide_additional_information {
            get {
                return ResourceManager.GetString("Use this area to provide additional information", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 物品价值 的本地化字符串。
        /// </summary>
        internal static string Value_of_goods {
            get {
                return ResourceManager.GetString("Value of goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 车辆模式 的本地化字符串。
        /// </summary>
        internal static string VehicleMode {
            get {
                return ResourceManager.GetString("VehicleMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 车辆咨询 的本地化字符串。
        /// </summary>
        internal static string Vehicle_consultation {
            get {
                return ResourceManager.GetString("Vehicle consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 航程纪录 的本地化字符串。
        /// </summary>
        internal static string Voyage_record {
            get {
                return ResourceManager.GetString("Voyage record", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 欢迎使用可追溯性配置系统 的本地化字符串。
        /// </summary>
        internal static string Welcome_to_Traceability_configuration_system {
            get {
                return ResourceManager.GetString("Welcome to Traceability configuration system", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否激活 的本地化字符串。
        /// </summary>
        internal static string Whether_activation {
            get {
                return ResourceManager.GetString("Whether activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否违约 的本地化字符串。
        /// </summary>
        internal static string Whether_default {
            get {
                return ResourceManager.GetString("Whether default", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否默认工厂 的本地化字符串。
        /// </summary>
        internal static string Whether_Default_factory {
            get {
                return ResourceManager.GetString("Whether Default factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 是否启用 的本地化字符串。
        /// </summary>
        internal static string Whether_Enable {
            get {
                return ResourceManager.GetString("Whether Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///  查找类似 工作编号 的本地化字符串。
        /// </summary>
        internal static string work_number {
            get {
                return ResourceManager.GetString("work number", resourceCulture);
            }
        }
    }
}
