//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGS_ProdPkgTOCfg
    {
        public int ID { get; set; }
        public string ProduceCategory { get; set; }
        public string ProduceLevel { get; set; }
        public string PartNo { get; set; }
        public string PartVersion { get; set; }
        public string QualityStatusCode { get; set; }
        public string PkgTypeCode { get; set; }
        public string ProducePlace { get; set; }
        public string OrigStkCode { get; set; }
        public string DestStkCode { get; set; }
        public string DestWHCode { get; set; }
        public bool AutoConfirm { get; set; }
        public bool AutoIssueAfterConfirm { get; set; }
        public bool AutoReceiveAfterIssue { get; set; }
        public bool AutoIssueBeforeReceive { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
