//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFG_ProductScanCfg
    {
        public MFG_ProductScanCfg()
        {
            this.MFG_ProductScanActionCfg = new HashSet<MFG_ProductScanActionCfg>();
            this.MFG_ProductScanOptParam = new HashSet<MFG_ProductScanOptParam>();
        }
    
        public int ID { get; set; }
        public string CfgID { get; set; }
        public string OrigProduceCategory { get; set; }
        public string OrigProduceLevel { get; set; }
        public string OrigPartNo { get; set; }
        public string OrigPartVersion { get; set; }
        public string OrigQualityStatus { get; set; }
        public string ScanSiteCode { get; set; }
        public string ScanOptGrp { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<MFG_ProductScanActionCfg> MFG_ProductScanActionCfg { get; set; }
        public virtual MFG_ScanOperateGroup MFG_ScanOperateGroup { get; set; }
        public virtual MFG_ScanSite MFG_ScanSite { get; set; }
        public virtual ICollection<MFG_ProductScanOptParam> MFG_ProductScanOptParam { get; set; }
    }
}
