//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFG_VehicleMode
    {
        public MFG_VehicleMode()
        {
            this.MFG_Part = new HashSet<MFG_Part>();
            this.MFG_Part1 = new HashSet<MFG_Part>();
        }
    
        public int ID { get; set; }
        public string VehicleMode { get; set; }
        public string VehicleName { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<MFG_Part> MFG_Part { get; set; }
        public virtual ICollection<MFG_Part> MFG_Part1 { get; set; }
    }
}
