//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFG_SelfCodeBindPartNoMap
    {
        public int ID { get; set; }
        public string PartNoMapCfg { get; set; }
        public string Description { get; set; }
        public string ParentPartNo { get; set; }
        public string ParentPartVersion { get; set; }
        public string ComponentPartNo { get; set; }
        public string ComponentPartVersion { get; set; }
        public bool Enabled { get; set; }
        public string CreateUserAccount { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateMachine { get; set; }
        public string LatestModifyUserAccount { get; set; }
        public System.DateTime LatestModifyTime { get; set; }
        public string LatestModifyMachine { get; set; }
    }
}
