//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFG_Part
    {
        public int ID { get; set; }
        public string PartNo { get; set; }
        public string PartVersion { get; set; }
        public string Description { get; set; }
        public string BriefDesc { get; set; }
        public string CompPartNo { get; set; }
        public string CompPartVersion { get; set; }
        public string ProduceCategory { get; set; }
        public string ProduceLevel { get; set; }
        public int DisplayOrder { get; set; }
        public string VehicleMode { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
        public string ForeColor { get; set; }
        public string BackColor { get; set; }
        public System.DateTime EffStartTime { get; set; }
        public System.DateTime EffEndTime { get; set; }
        public bool ForceDisable { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual MFG_ProduceCategory MFG_ProduceCategory { get; set; }
        public virtual MFG_VehicleMode MFG_VehicleMode { get; set; }
        public virtual MFG_VehicleMode MFG_VehicleMode1 { get; set; }
    }
}
