//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFG_ScanSite
    {
        public MFG_ScanSite()
        {
            this.MFG_ProductScanCfg = new HashSet<MFG_ProductScanCfg>();
            this.SYS_ProgScanSite = new HashSet<SYS_ProgScanSite>();
            this.SYS_RoleScanSitePriv = new HashSet<SYS_RoleScanSitePriv>();
        }
    
        public int ID { get; set; }
        public string ScanSiteCode { get; set; }
        public string ScanSiteName { get; set; }
        public bool RestrictProduceType { get; set; }
        public bool RestrictProdLine { get; set; }
        public string WCCode { get; set; }
        public string ScanSiteType { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string SeqCheckField { get; set; }
        public string DeviceID { get; set; }
    
        public virtual ICollection<MFG_ProductScanCfg> MFG_ProductScanCfg { get; set; }
        public virtual ICollection<SYS_ProgScanSite> SYS_ProgScanSite { get; set; }
        public virtual ICollection<SYS_RoleScanSitePriv> SYS_RoleScanSitePriv { get; set; }
    }
}
