//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFG_ProductScanActionCfg
    {
        public int ID { get; set; }
        public string CfgID { get; set; }
        public string ActionCode { get; set; }
        public string TargetProduceCategory { get; set; }
        public string TargetProduceLevel { get; set; }
        public string TargetPartNo { get; set; }
        public string TargetPartVersion { get; set; }
        public string TargetQualityStatus { get; set; }
        public string TargetScanSite { get; set; }
        public string RctStk { get; set; }
        public string IssueStk { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual MFG_ProductScanCfg MFG_ProductScanCfg { get; set; }
        public virtual MFG_ScanAction MFG_ScanAction { get; set; }
    }
}
