//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFG_ScanPlugin
    {
        public MFG_ScanPlugin()
        {
            this.MFG_ProductScanOptParam = new HashSet<MFG_ProductScanOptParam>();
            this.MFG_ScanOperateDetail = new HashSet<MFG_ScanOperateDetail>();
            this.MFG_ScanPluginParam = new HashSet<MFG_ScanPluginParam>();
        }
    
        public long ID { get; set; }
        public string PluginID { get; set; }
        public string PluginName { get; set; }
        public string PluginType { get; set; }
        public string PluginDesc { get; set; }
        public string PluginStage { get; set; }
        public string PluginForm { get; set; }
        public bool UseDeviceComm { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<MFG_ProductScanOptParam> MFG_ProductScanOptParam { get; set; }
        public virtual ICollection<MFG_ScanOperateDetail> MFG_ScanOperateDetail { get; set; }
        public virtual ICollection<MFG_ScanPluginParam> MFG_ScanPluginParam { get; set; }
    }
}
