//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFG_BOM
    {
        public int ID { get; set; }
        public string ParentPartNo { get; set; }
        public string ComponentPartNo { get; set; }
        public string Ref1 { get; set; }
        public System.DateTime EffStartTime { get; set; }
        public System.DateTime EffExpireTime { get; set; }
        public double Qty { get; set; }
        public string Type { get; set; }
        public int Op { get; set; }
        public float Scrp { get; set; }
    }
}
