//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Prog
    {
        public SYS_Prog()
        {
            this.SYS_ProgScanSite = new HashSet<SYS_ProgScanSite>();
            this.SYS_ProgPriv = new HashSet<SYS_ProgPriv>();
        }
    
        public int ID { get; set; }
        public string ProgCode { get; set; }
        public string ProgName { get; set; }
        public string ProgType { get; set; }
        public string ProgForm { get; set; }
        public string AppType { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<SYS_ProgScanSite> SYS_ProgScanSite { get; set; }
        public virtual ICollection<SYS_ProgPriv> SYS_ProgPriv { get; set; }
    }
}
