//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_PackingType
    {
        public WMS_PackingType()
        {
            this.WMS_ProductBinConfig = new HashSet<WMS_ProductBinConfig>();
        }
    
        public string PackingTypeCode { get; set; }
        public int ID { get; set; }
        public string PackingTypeName { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<WMS_ProductBinConfig> WMS_ProductBinConfig { get; set; }
    }
}
