//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_TransHist
    {
        public int ID { get; set; }
        public string QADTransType { get; set; }
        public string SAPTransType { get; set; }
        public string OrderID { get; set; }
        public string ItemCode { get; set; }
        public string SupCode { get; set; }
        public string RegionCode { get; set; }
        public string Location { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime EffDate { get; set; }
        public double TransQty { get; set; }
        public string CreateUser { get; set; }
        public string AdjustReason { get; set; }
        public string Receiver { get; set; }
        public string ERPSys { get; set; }
        public Nullable<double> KpQty { get; set; }
        public string KpStatus { get; set; }
        public string BillTo { get; set; }
        public string Lot { get; set; }
        public string Account { get; set; }
        public string SubAccount { get; set; }
        public string CostCenter { get; set; }
        public string CostProject { get; set; }
        public Nullable<System.DateTime> MESEffDate { get; set; }
        public string ImmMould { get; set; }
        public int DssID { get; set; }
        public bool SAPSyncStatus { get; set; }
    }
}
