//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WMS_WareHouse
    {
        public WMS_WareHouse()
        {
            this.WMS_ProductShelfStkMap = new HashSet<WMS_ProductShelfStkMap>();
            this.WMS_Shelf = new HashSet<WMS_Shelf>();
        }
    
        public string WHCode { get; set; }
        public int ID { get; set; }
        public string WHName { get; set; }
        public string FactoryCode { get; set; }
        public bool Enabled { get; set; }
        public bool IsDelete { get; set; }
        public string CreateUserAccount { get; set; }
        public string CreateMachine { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual ICollection<WMS_ProductShelfStkMap> WMS_ProductShelfStkMap { get; set; }
        public virtual ICollection<WMS_Shelf> WMS_Shelf { get; set; }
    }
}
